apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: replicaset-conversao-temperatura
  labels: 
    app: web
spec:
  template:
    metadata:
      name: pod-conversao-temperatura
      labels:
        app: web
    spec:
      containers:
        - image: tiagomendessilva/conversao-temperatura:v2
          name: site
          ports:
            - containerPort: 8080
  replicas: 2
  selector:
    matchLabels:
      app: web